# Generated by Django 5.0.2 on 2024-02-13 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_is_sale_product_sale_end_product_sale_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sale_end',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sale_start',
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.FloatField(),
        ),
    ]
